theme="jetbrains_dark"
[editor]
# bufferline = "multiple"
line-number = "relative"
cursorline= true
color-modes = true
auto-pairs = false
true-color = true
mouse = true
rulers = [120]

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator", "version-control"]
center = ["diagnostics"]
right = ["position","total-line-numbers", "file-encoding", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden=false
