[[language]]
name = "python"
auto-format=true
roots = ["pyproject.toml"]

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[[language]]
name = "html"
roots = [".git"]
auto-format = false
language-servers = ["emmet-lsp"]
formatter = { command = 'prettier', args = ["--parser", "html", "--print-width", "9999"] }

[[language]]
name = "cpp"
language-servers = [ "ccls" ]

[language-server.ccls]
command = "ccls"
args = ["--stdio"]

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }


